Angular springboot crud
jayeshsony/Angular-Springboot-Crud pull request #1
Opened 2024-06-18 06:55 UTC by jayeshsony

2024-06-18 16:41 UTC, KrushaliTalaviya requested changes

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/AngularSpringbootCrudApplication.java
> +
Remove this line

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/controller/EmployeeController.java
> +
Remove this line

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/dto/constantmessages/ConstantMessages.java
> +	private ConstantMessages() {
No need to add this

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +		if (id != null && empRepo.existsById(id)) {
Add proper name

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +	EmployeeRepository empRepo;
Add blank line after this

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +		Long id = employeeDTO.getId();
You can write below like  employeeDTO.getId() != null

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +		return ResponseEntity.ok(modelMapper.map(savedEmployee, EmployeeDto.class));
You can write  ResponseEntity.ok(modelMapper.map(empRepo.save(employee), EmployeeDto.class));

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +		return allEmployees;
You can return directly  empRepo.findAll(Sort.by(Direction.DESC, "id"));

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/java/com/service/impl/EmployeeServiceImpl.java
> +			Optional<Employee> foundEmployee = empRepo.findById(id);
Please add proper name

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Backend/src/main/resources/application.properties
> +spring.mvc.view.suffix=.jsp
Add blank line after this and removed unnecessary properties

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Frontend/src/app/employee-list/employee-list.component.html
> +          <li><a style="text-decoration: none;" routerLink="../create" routerLinkActive="active"><svg
Removed all incline css

2024-06-18 16:41 UTC, KrushaliTalaviya commented on Angular-Springboot-Crud-Frontend/src/app/employee.ts
> +    firstName: string = "";
You can write like below firstName!: string;

2024-06-19 04:09 UTC, jayeshsony commented
Created PR cahnges

2024-06-19 05:22 UTC, jayeshsony commented
Created PR changes

2024-06-19 09:39 UTC, KrushaliTalaviya approved these changes

2024-06-19 09:39 UTC, merged